
#+TITLE: Operational Feature Selection in Gaussian Mixture Models
#+AUTHOR: Adrien Lagrange
#+EMAIL: ad.lagrange@gmail.com

* General
  This is a remote module for the ORFEO Toolbox(https://www.orfeo-toolbox.org/). It is designed to work with OTBv5 modular system and to be places in OTB/Module/Remote.
  
  This module implements a method to perform a fast forward feature selection using a Gaussian Mixture Model. The algorithm is based on the following papers http://arxiv.org/abs/1501.00857 and Nonlinear parsimonious feature selection for the classification of hyperspectral images (http://fauvel.mathieu.free.fr/pdfs/pgpda_grsl.pdf).

* Getting Started

In addition of the C++ class, this module contains 3 OTB applications:
- otbcli_TrainGMMApp: Train a GMM classifier from multiple pairs of images and training vector data. It also allows to perform ridge regularization with an embedded selection of the regularization parameter among a list of proposed values.
- otbcli_TrainGMMSelectionApp: Train a GMM classifier and in addition perform a feature selection algorithm (SFS, SFFS) with various possible criterion (Jeffries-Matusita dist., Kullback-Lieber div., Cohen's kappa, overall accuracy, mean F1-score).
- otbcli_PredictGMMApp: Perform a classification of the input image according to a GMM model file created by one of two previous applications.

* License

  This software is distributed under the Apache License. Please see LICENSE for details.

* Author

  Adrien Lagrange

* Thanks

  It is a fork of the ORFEO ToolBox template module provided by Manuel Grizonnet
  (https://github.com/orfeotoolbox/otbExternalModuleTemplate.git) and which is itself a fork of the ITK template module provided by Bradley Lowekamp
  (https://github.com/blowekamp/itkExternalTemplate.git) which was adapted for the
  ORFEO ToolBox.
